spring.application.name=traceline-backend
# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=traceline
spring.data.mongodb.uri=mongodb://localhost:27017/traceline
spring.data.mongodb.auto-index-creation=true

# Server
server.port=9090
server.servlet.context-path=/api

# JWT
jwt.secret=12aef90fd883ba6100d49e95f0f38e55a0150853741e9c5e36abb10b338b65c2
jwt.expiration.ms=86400000

## AI Engine (simulated or real endpoint)
#ai.engine.url=http://localhost:5000/predict   # optional Python service

# Logging
logging.level.com.traceline=DEBUG

# Ethereum Blockchain Configuration
blockchain.rpc-url=http://127.0.0.1:7545
#blockchain.private-key=0xdab4aa1e9d0e2db3d122d40cd3198a4c3f1ec1e41b8cdaf5a5097260403a3306
#blockchain.gas-limit=6721975
#blockchain.gas-price=20000000000
#blockchain.contract-address=0xd8b934580fcE35a11B58C6D73aDeE468a2833fa8  # Will be filled after deployment
#blockchain.enabled=true

# Ganache Local Node (your CLI is running on this)
#web3j.client-address=http://127.0.0.1:7545

# Your imported account's private key (from Ganache CLI)
ethereum.private-key=0x207e8a7b65c91ec1591553bf5ba9a386361202e7af21c812d13eb4098e9c04a7

# Contract address (you'll get this after deployment)
ethereum.contract-address=0x7751258BA362F608848f59C0f6D073148EB000Df