spring.application.name=traceline-backend
# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=traceline
spring.data.mongodb.uri=mongodb://localhost:27017/traceline

# Server
server.port=9090
server.servlet.context-path=/api

# JWT
jwt.secret=12aef90fd883ba6100d49e95f0f38e55a0150853741e9c5e36abb10b338b65c2
jwt.expiration.ms=86400000

## AI Engine (simulated or real endpoint)
#ai.engine.url=http://localhost:5000/predict   # optional Python service

# Logging
logging.level.com.traceline=DEBUG